In [1]:
# Import Dependencies
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# Load the data
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [3]:
# View train data
train_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,RENT,28000.0,Not Verified,high_risk,n,...,100.0,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0,N,N
12176,354944,354944,15000.0,0.1774,540.34,RENT,50000.0,Verified,high_risk,n,...,90.5,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0,N,N
12177,354973,354973,3600.0,0.1862,131.28,RENT,60000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0,N,N
12178,355002,355002,15000.0,0.0881,475.68,MORTGAGE,62000.0,Source Verified,high_risk,n,...,100.0,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0,N,N
12179,355307,355307,15000.0,0.1774,540.34,RENT,54080.0,Not Verified,high_risk,n,...,90.0,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0,N,N

In [4]:
# Create a training set from the 2019 loans csv
_2019_loans = train_df.drop(columns=['Unnamed: 0','index','loan_status'], axis=1)
_2019_loans

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,n,29.99,0.0,0.0,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,n,11.26,2.0,0.0,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,n,11.28,0.0,0.0,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,n,18.08,0.0,0.0,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,n,27.77,0.0,2.0,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,19975.0,0.2565,801.09,RENT,28000.0,Not Verified,n,28.42,0.0,0.0,...,100.0,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0,N,N
12176,15000.0,0.1774,540.34,RENT,50000.0,Verified,n,23.43,4.0,0.0,...,90.5,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0,N,N
12177,3600.0,0.1862,131.28,RENT,60000.0,Not Verified,n,28.80,0.0,1.0,...,100.0,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0,N,N
12178,15000.0,0.0881,475.68,MORTGAGE,62000.0,Source Verified,n,11.44,0.0,0.0,...,100.0,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0,N,N
12179,15000.0,0.1774,540.34,RENT,54080.0,Not Verified,n,21.66,1.0,1.0,...,90.0,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0,N,N

In [5]:
_2019_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   12180 non-null  float64
 1   int_rate                    12180 non-null  float64
 2   installment                 12180 non-null  float64
 3   home_ownership              12180 non-null  object
 4   annual_inc                  12180 non-null  float64
 5   verification_status         12180 non-null  object
 6   pymnt_plan                  12180 non-null  object
 7   dti                         12180 non-null  float64
 8   delinq_2yrs                 12180 non-null  float64
 9   inq_last_6mths              12180 non-null  float64
 10  open_acc                    12180 non-null  float64
 11  pub_rec                     12180 non-null  float64
 12  revol_bal                   12180 non-null  float64
 13  total_acc                   12180 non-null  float64
 14  initial_list_status         12180 non-null  object
 15  out_prncp                   12180 non-null  float64
 16  out_prncp_inv               12180 non-null  float64
 17  total_pymnt                 12180 non-null  float64
 18  total_pymnt_inv             12180 non-null  float64
 19  total_rec_prncp             12180 non-null  float64
 20  total_rec_int               12180 non-null  float64
 21  total_rec_late_fee          12180 non-null  float64
 22  recoveries                  12180 non-null  float64
 23  collection_recovery_fee     12180 non-null  float64
 24  last_pymnt_amnt             12180 non-null  float64
 25  collections_12_mths_ex_med  12180 non-null  float64
 26  policy_code                 12180 non-null  float64
 27  application_type            12180 non-null  object
 28  acc_now_delinq              12180 non-null  float64
 29  tot_coll_amt                12180 non-null  float64
 30  tot_cur_bal                 12180 non-null  float64
 31  open_acc_6m                 12180 non-null  float64
 32  open_act_il                 12180 non-null  float64
 33  open_il_12m                 12180 non-null  float64
 34  open_il_24m                 12180 non-null  float64
 35  mths_since_rcnt_il          12180 non-null  float64
 36  total_bal_il                12180 non-null  float64
 37  il_util                     12180 non-null  float64
 38  open_rv_12m                 12180 non-null  float64
 39  open_rv_24m                 12180 non-null  float64
 40  max_bal_bc                  12180 non-null  float64
 41  all_util                    12180 non-null  float64
 42  total_rev_hi_lim            12180 non-null  float64
 43  inq_fi                      12180 non-null  float64
 44  total_cu_tl                 12180 non-null  float64
 45  inq_last_12m                12180 non-null  float64
 46  acc_open_past_24mths        12180 non-null  float64
 47  avg_cur_bal                 12180 non-null  float64
 48  bc_open_to_buy              12180 non-null  float64
 49  bc_util                     12180 non-null  float64
 50  chargeoff_within_12_mths    12180 non-null  float64
 51  delinq_amnt                 12180 non-null  float64
 52  mo_sin_old_il_acct          12180 non-null  float64
 53  mo_sin_old_rev_tl_op        12180 non-null  float64
 54  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 55  mo_sin_rcnt_tl              12180 non-null  float64
 56  mort_acc                    12180 non-null  float64
 57  mths_since_recent_bc        12180 non-null  float64
 58  mths_since_recent_inq       12180 non-null  float64
 59  num_accts_ever_120_pd       12180 non-null  float64
 60  num_actv_bc_tl              12180 non-null  float64
 61  num_actv_rev_tl             12180 non-null  float64
 62  num_bc_sats                 12180 non-null  float64
 63  num_bc_tl                   12180 non-null  float64
 64  num_il_tl                   12180 non-null  float64
 65  num_op_rev_tl               12180 non-null  float64
 66  num_rev_accts               12180 non-null  float64
 67  num_rev_tl_bal_gt_0         12180 non-null  float64
 68  num_sats                    12180 non-null  float64
 69  num_tl_120dpd_2m            12180 non-null  float64
 70  num_tl_30dpd                12180 non-null  float64
 71  num_tl_90g_dpd_24m          12180 non-null  float64
 72  num_tl_op_past_12m          12180 non-null  float64
 73  pct_tl_nvr_dlq              12180 non-null  float64
 74  percent_bc_gt_75            12180 non-null  float64
 75  pub_rec_bankruptcies        12180 non-null  float64
 76  tax_liens                   12180 non-null  float64
 77  tot_hi_cred_lim             12180 non-null  float64
 78  total_bal_ex_mort           12180 non-null  float64
 79  total_bc_limit              12180 non-null  float64
 80  total_il_high_credit_limit  12180 non-null  float64
 81  hardship_flag               12180 non-null  object
 82  debt_settlement_flag        12180 non-null  object
dtypes: float64(76), object(7)
memory usage: 7.7+ MB

In [6]:
# Convert categorical data to numeric and separate target feature for training data
# One-hot encoding the entire dataframe
X_TR_Dummies=pd.get_dummies(_2019_loans)
print(X_TR_Dummies.columns)
X_TR_Dummies

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N',
       'debt_settlement_flag_Y'],
      dtype='object')

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,0.0,39728.0,...,0,1,0,1,1,0,1,0,1,0
1,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,0.0,9585.0,...,0,1,0,1,1,0,1,0,1,0
2,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,0.0,16708.0,...,0,1,0,1,1,0,1,0,1,0
3,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,1.0,8809.0,...,0,1,0,1,1,0,1,0,1,0
4,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,0.0,65420.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,19975.0,0.2565,801.09,28000.0,28.42,0.0,0.0,15.0,0.0,9679.0,...,0,1,0,1,1,0,1,0,1,0
12176,15000.0,0.1774,540.34,50000.0,23.43,4.0,0.0,16.0,0.0,3193.0,...,1,1,0,1,1,0,1,0,1,0
12177,3600.0,0.1862,131.28,60000.0,28.80,0.0,1.0,14.0,0.0,11804.0,...,0,1,0,1,1,0,1,0,1,0
12178,15000.0,0.0881,475.68,62000.0,11.44,0.0,0.0,5.0,0.0,157.0,...,0,1,0,1,0,1,1,0,1,0
12179,15000.0,0.1774,540.34,54080.0,21.66,1.0,1.0,5.0,0.0,8349.0,...,0,1,1,0,1,0,1,0,1,0

In [7]:
# Create a test set from the 2019 loans csv
y_tr_dummies = train_df['loan_status']
y_tr_dummies.unique()

array(['low_risk', 'high_risk'], dtype=object)

In [8]:
# Convert categorical data to numeric and separate target feature for testing data
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

# Converting output labels to 0 and 1
y_tr_dummies = LabelEncoder().fit_transform(y_tr_dummies)
y_tr_dummies

array([1, 1, 1, ..., 0, 0, 0])

In [9]:
# View test info
test_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,25429,25429,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,38496,38496,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,19667,19667,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,37505,37505,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,77282,77282,30000.0,0.1240,673.42,RENT,140480.0,Source Verified,high_risk,n,...,100.0,28.6,0.0,0.0,159688.0,110873.0,48400.0,107388.0,N,N
4698,77291,77291,24000.0,0.0756,747.22,RENT,50000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,62375.0,18928.0,13300.0,30775.0,N,N
4699,77292,77292,10000.0,0.2305,387.36,RENT,33000.0,Verified,high_risk,n,...,100.0,0.0,0.0,0.0,43250.0,33022.0,8500.0,29550.0,N,N
4700,77297,77297,8000.0,0.1862,205.86,RENT,38000.0,Source Verified,high_risk,n,...,95.0,0.0,1.0,0.0,31357.0,19595.0,1500.0,9657.0,N,N
4701,77304,77304,30000.0,0.2055,1123.34,RENT,180000.0,Source Verified,high_risk,n,...,100.0,33.3,0.0,0.0,218686.0,209389.0,5600.0,209986.0,N,N

In [10]:
# Create a testing set from the 2020 loans csv
_2020_loans = test_df.drop(columns=['Unnamed: 0','index','loan_status'], axis=1)
_2020_loans

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,n,19.75,0.0,1.0,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,n,11.52,2.0,0.0,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,n,6.74,0.0,0.0,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,n,12.13,0.0,2.0,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,n,16.08,0.0,3.0,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,30000.0,0.1240,673.42,RENT,140480.0,Source Verified,n,15.74,0.0,0.0,...,100.0,28.6,0.0,0.0,159688.0,110873.0,48400.0,107388.0,N,N
4698,24000.0,0.0756,747.22,RENT,50000.0,Not Verified,n,26.81,0.0,0.0,...,100.0,0.0,0.0,0.0,62375.0,18928.0,13300.0,30775.0,N,N
4699,10000.0,0.2305,387.36,RENT,33000.0,Verified,n,38.51,0.0,2.0,...,100.0,0.0,0.0,0.0,43250.0,33022.0,8500.0,29550.0,N,N
4700,8000.0,0.1862,205.86,RENT,38000.0,Source Verified,n,16.36,0.0,1.0,...,95.0,0.0,1.0,0.0,31357.0,19595.0,1500.0,9657.0,N,N
4701,30000.0,0.2055,1123.34,RENT,180000.0,Source Verified,n,12.06,0.0,0.0,...,100.0,33.3,0.0,0.0,218686.0,209389.0,5600.0,209986.0,N,N

In [11]:
_2020_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4702 entries, 0 to 4701
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   4702 non-null   float64
 1   int_rate                    4702 non-null   float64
 2   installment                 4702 non-null   float64
 3   home_ownership              4702 non-null   object
 4   annual_inc                  4702 non-null   float64
 5   verification_status         4702 non-null   object
 6   pymnt_plan                  4702 non-null   object
 7   dti                         4702 non-null   float64
 8   delinq_2yrs                 4702 non-null   float64
 9   inq_last_6mths              4702 non-null   float64
 10  open_acc                    4702 non-null   float64
 11  pub_rec                     4702 non-null   float64
 12  revol_bal                   4702 non-null   float64
 13  total_acc                   4702 non-null   float64
 14  initial_list_status         4702 non-null   object
 15  out_prncp                   4702 non-null   float64
 16  out_prncp_inv               4702 non-null   float64
 17  total_pymnt                 4702 non-null   float64
 18  total_pymnt_inv             4702 non-null   float64
 19  total_rec_prncp             4702 non-null   float64
 20  total_rec_int               4702 non-null   float64
 21  total_rec_late_fee          4702 non-null   float64
 22  recoveries                  4702 non-null   float64
 23  collection_recovery_fee     4702 non-null   float64
 24  last_pymnt_amnt             4702 non-null   float64
 25  collections_12_mths_ex_med  4702 non-null   float64
 26  policy_code                 4702 non-null   float64
 27  application_type            4702 non-null   object
 28  acc_now_delinq              4702 non-null   float64
 29  tot_coll_amt                4702 non-null   float64
 30  tot_cur_bal                 4702 non-null   float64
 31  open_acc_6m                 4702 non-null   float64
 32  open_act_il                 4702 non-null   float64
 33  open_il_12m                 4702 non-null   float64
 34  open_il_24m                 4702 non-null   float64
 35  mths_since_rcnt_il          4702 non-null   float64
 36  total_bal_il                4702 non-null   float64
 37  il_util                     4702 non-null   float64
 38  open_rv_12m                 4702 non-null   float64
 39  open_rv_24m                 4702 non-null   float64
 40  max_bal_bc                  4702 non-null   float64
 41  all_util                    4702 non-null   float64
 42  total_rev_hi_lim            4702 non-null   float64
 43  inq_fi                      4702 non-null   float64
 44  total_cu_tl                 4702 non-null   float64
 45  inq_last_12m                4702 non-null   float64
 46  acc_open_past_24mths        4702 non-null   float64
 47  avg_cur_bal                 4702 non-null   float64
 48  bc_open_to_buy              4702 non-null   float64
 49  bc_util                     4702 non-null   float64
 50  chargeoff_within_12_mths    4702 non-null   float64
 51  delinq_amnt                 4702 non-null   float64
 52  mo_sin_old_il_acct          4702 non-null   float64
 53  mo_sin_old_rev_tl_op        4702 non-null   float64
 54  mo_sin_rcnt_rev_tl_op       4702 non-null   float64
 55  mo_sin_rcnt_tl              4702 non-null   float64
 56  mort_acc                    4702 non-null   float64
 57  mths_since_recent_bc        4702 non-null   float64
 58  mths_since_recent_inq       4702 non-null   float64
 59  num_accts_ever_120_pd       4702 non-null   float64
 60  num_actv_bc_tl              4702 non-null   float64
 61  num_actv_rev_tl             4702 non-null   float64
 62  num_bc_sats                 4702 non-null   float64
 63  num_bc_tl                   4702 non-null   float64
 64  num_il_tl                   4702 non-null   float64
 65  num_op_rev_tl               4702 non-null   float64
 66  num_rev_accts               4702 non-null   float64
 67  num_rev_tl_bal_gt_0         4702 non-null   float64
 68  num_sats                    4702 non-null   float64
 69  num_tl_120dpd_2m            4702 non-null   float64
 70  num_tl_30dpd                4702 non-null   float64
 71  num_tl_90g_dpd_24m          4702 non-null   float64
 72  num_tl_op_past_12m          4702 non-null   float64
 73  pct_tl_nvr_dlq              4702 non-null   float64
 74  percent_bc_gt_75            4702 non-null   float64
 75  pub_rec_bankruptcies        4702 non-null   float64
 76  tax_liens                   4702 non-null   float64
 77  tot_hi_cred_lim             4702 non-null   float64
 78  total_bal_ex_mort           4702 non-null   float64
 79  total_bc_limit              4702 non-null   float64
 80  total_il_high_credit_limit  4702 non-null   float64
 81  hardship_flag               4702 non-null   object
 82  debt_settlement_flag        4702 non-null   object
dtypes: float64(76), object(7)
memory usage: 3.0+ MB

In [12]:
# Convert categorical data to numeric and separate target feature for training data
# One-hot encoding the entire dataframe
X_TE_Dummies=pd.get_dummies(_2020_loans)
print(X_TE_Dummies.columns)
X_TE_Dummies

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N'],
      dtype='object')

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,0.0,9471.0,...,0,0,1,0,1,1,0,1,0,1
1,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,0.0,1280.0,...,0,0,1,0,1,1,0,1,0,1
2,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,0.0,4757.0,...,0,0,1,0,1,1,0,1,0,1
3,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,0.0,12731.0,...,0,0,1,0,1,1,0,1,0,1
4,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,0.0,10413.0,...,0,0,1,0,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,30000.0,0.1240,673.42,140480.0,15.74,0.0,0.0,20.0,0.0,23215.0,...,1,0,1,1,0,1,0,1,0,1
4698,24000.0,0.0756,747.22,50000.0,26.81,0.0,0.0,9.0,0.0,459.0,...,0,0,1,0,1,1,0,1,0,1
4699,10000.0,0.2305,387.36,33000.0,38.51,0.0,2.0,7.0,0.0,6342.0,...,0,1,1,1,0,1,0,1,0,1
4700,8000.0,0.1862,205.86,38000.0,16.36,0.0,1.0,8.0,1.0,11636.0,...,1,0,1,0,1,1,0,1,0,1
4701,30000.0,0.2055,1123.34,180000.0,12.06,0.0,0.0,8.0,0.0,4771.0,...,1,0,1,1,0,1,0,1,0,1

In [13]:
# Create a test set from the 2020Q1 loans csv
y_te_dummies = test_df['loan_status']
y_te_dummies.unique()

array(['low_risk', 'high_risk'], dtype=object)

In [14]:
# Convert categorical data to numeric and separate target feature for testing data

# Converting output labels to 0 and 1
y_te_dummies = LabelEncoder().fit_transform(y_te_dummies)
y_te_dummies

array([1, 1, 1, ..., 0, 0, 0])

In [15]:
test_df['debt_settlement_flag'].unique()

array(['N'], dtype=object)

In [16]:
# add missing dummy variables to testing set
# Add 2019 category to 2020 test set
add_data = X_TR_Dummies["debt_settlement_flag_Y"]
X_TE_Dummies = X_TE_Dummies.join(add_data)

In [17]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model

LogisticRegression()

In [18]:
# Fit the training model using the training data
model.fit(X_TR_Dummies, y_tr_dummies)

/Users/nepanji/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
# Print the training and test scores
print(f"Training Score: {model.score(X_TR_Dummies, y_tr_dummies)}")
print(f"Testing Score: {model.score(X_TE_Dummies, y_te_dummies)}")

Training Score: 0.6511494252873563
Testing Score: 0.5163760102084219

In [20]:
# Create Confusion Matrix of the predicted vs the actual outcomes
from sklearn.metrics import confusion_matrix

y_true = y_te_dummies
y_pred = model.predict(X_TE_Dummies)
confusion_matrix(y_true, y_pred)

array([[ 711, 1640],
       [ 634, 1717]])

In [21]:
# Create the Classification Report and compare
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.53      0.30      0.38      2351
           1       0.51      0.73      0.60      2351

    accuracy                           0.52      4702
   macro avg       0.52      0.52      0.49      4702
weighted avg       0.52      0.52      0.49      4702

In [22]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_TR_Dummies, y_tr_dummies)

In [23]:
print(f'Training Score: {clf.score(X_TR_Dummies, y_tr_dummies)}')
print(f'Testing Score: {clf.score(X_TE_Dummies, y_te_dummies)}')

Training Score: 1.0
Testing Score: 0.6433432581880051

In [24]:
# Create Confusion Matrix of the predicted vs the actual outcomes
from sklearn.metrics import confusion_matrix

y_true = y_te_dummies
y_pred = clf.predict(X_TE_Dummies)
confusion_matrix(y_true, y_pred)

array([[1888,  463],
       [1214, 1137]])

In [25]:
# Create the Classification Report and compare
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.61      0.80      0.69      2351
           1       0.71      0.48      0.58      2351

    accuracy                           0.64      4702
   macro avg       0.66      0.64      0.63      4702
weighted avg       0.66      0.64      0.63      4702

In [26]:
# Scale the data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_TR_Dummies)
#use this new scaling to transform our training data
X_TR_Dummies_scaled = scaler.transform(X_TR_Dummies)
X_TE_Dummies_scaled = scaler.transform(X_TE_Dummies)

In [27]:
# Train the Logistic Regression model on the scaled data and print the model score

scaled_model = LogisticRegression()
scaled_model.fit(X_TR_Dummies_scaled, y_tr_dummies)
print(f'Training Score: {scaled_model.score(X_TR_Dummies_scaled, y_tr_dummies)}')
print(f'Testing Score: {scaled_model.score(X_TE_Dummies_scaled, y_te_dummies)}')

Training Score: 0.7078817733990148
Testing Score: 0.767333049766057

/Users/nepanji/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [28]:
# Create Confusion Matrix of the predicted vs the actual outcomes
from sklearn.metrics import confusion_matrix

y_true = y_te_dummies
y_pred = scaled_model.predict(X_TE_Dummies_scaled)
confusion_matrix(y_true, y_pred)

array([[1789,  562],
       [ 532, 1819]])

In [29]:
# Create the Classification Report and compare
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.76      0.77      2351
           1       0.76      0.77      0.77      2351

    accuracy                           0.77      4702
   macro avg       0.77      0.77      0.77      4702
weighted avg       0.77      0.77      0.77      4702

In [30]:
# Train a Random Forest Classifier model on the scaled data and print the model score
scaled_clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_TR_Dummies_scaled, y_tr_dummies)
print(f'Training Score: {scaled_clf.score(X_TR_Dummies_scaled, y_tr_dummies)}')
print(f'Testing Score: {scaled_clf.score(X_TE_Dummies_scaled, y_te_dummies)}')

Training Score: 1.0
Testing Score: 0.6420672054444917

In [31]:
# Create Confusion Matrix of the predicted vs the actual outcomes
from sklearn.metrics import confusion_matrix

y_true = y_te_dummies
y_pred = model.predict(X_TE_Dummies_scaled)
confusion_matrix(y_true, y_pred)

array([[ 496, 1855],
       [ 503, 1848]])

In [32]:
# Create the Classification Report and compare
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.21      0.30      2351
           1       0.50      0.79      0.61      2351

    accuracy                           0.50      4702
   macro avg       0.50      0.50      0.45      4702
weighted avg       0.50      0.50      0.45      4702